---
title: "park_net200_drop0.1"
author: "Francesco Migliaccio"
date: "2024-12-02"
output: html_document
---

Here we have the ground truth
```{r source net}

net200 <- readRDS("/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Active_Cold_VS_Cold/net200.RDS")

# Costruiamo la rete mediante il comando della libreria "netUtils"
#net200 <- netUtils::sample_lfr(n = 200, mu = 0.01, average_degree = 10,
                    # max_degree = 15, min_community = 10, max_community = 30)


# Vogliamo che la rete abbia una sparsità di circa il 95%, cioè rispetto ad una fully connected deve avere solo il 5% di edges:

# Per verificarlo prendiamo la matrice di adiacenza della rete, A:

A = as.matrix(igraph::as_adjacency_matrix(net200))

(netspar <- 1-sum(A!=0)/length(A))

rafalib::imagemat(A!=0)
# Osserviamo i degree dei nodi
igraph::degree(net200)

#saveRDS(net200, file = "/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Active_Cold_VS_Cold/net200.RDS")

meandeg <- mean(degree(net200))

```

Generating data pre-zeroinflation:
```{r loading generation}

source("/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/ZINB_Generating_Data_Functions.R")


# Selecting five seeds, each one is the starting point to generate H matrices representing the ground truth
SEED <- c(1926, 2, 7, 173, 8130)

# Impostiamo k, nel paper h, numero di esperimenti cioè matrici
k = 3
# Le media dovranno essere k medie


# Il numero di nodi è determinato dalla rete
p = length(net200)


k_mat <- list()
for (i in 1:length(SEED)){
  k_mat[[i]] <- k_net_datagen(net = net200, k = k, seed = SEED[i], n = 100, p = p, theta = 0.125, means = c(3,6,9), zerop = 0.1)
} # vedere più su per dettagli della funzione linea 97


# Andiamo a vedere queste matrici, in particolare in nero abbiamo gli elementi diversi da zero, che aumentano all'aumentare delle medie
rafalib::imagemat(k_mat[[1]][[1]]!=0)

rafalib::imagemat(k_mat[[1]][[3]]!=0)

```

Let's take a quick look to the data:
```{r explorative analysis, fig.width=20, fig.height=16}
library(igraph)
# Abbiamo k matrici di p colonne corrispondenti a p geni interconnessi

dim(k_mat[[1]][[1]])

# Visualizziamola in plot

plot(net200,
     vertex.size = 5,
     vertex.label = NA) 

# Verifichiamo i degree dei nodi della network

paste("network degree:", igraph::degree(net200), sep = " ")

paste("mean network degree:", mean(igraph::degree(net200)), sep = " ")

hist(igraph::degree(net200), col = "azure3", main = "Node Degrees Freqency")

# Salviamo le matrici in un oggetto Xs:

Xs_0.1 <- k_mat

saveRDS(Xs_0.1, file = "/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/net200_n100_Xs_01.RDS")

```



```{r early integration with our method}

source("/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/R/Main_Functions.R")
source("/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/R/Aux_Functions.R")

available = parallel::detectCores(logical = FALSE)
ncores <- available - 1 


Xs_0.1_early <- lapply(Xs_0.1, function(x) do.call(rbind,x))
# Per far funzionare il nostro metodo dobbiamo fornire alla funzione comunque una lista anche se di un solo elemento quando si ha una sola matrice
Xs_0.1_early_list <- lapply(Xs_0.1_early, list)

# Qui salveremo i tempi impiegati da ciascuna realizzazione
running_time <- list()
# Qui l'output
net200_results <- list()

for (i in 1:length(Xs_0.1)){
  running_time[[i]] <- system.time({
    net200_results[[i]] <- zinb_LGM_grp(Xs_0.1_early_list[[i]], sym = "AND", nCores = ncores, verbose = 1)
  })[3]
}

mean(sapply(running_time, function(x) x/60))

saveRDS(net200_results, file = "/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/grouped_early_res_0.1.RDS")
saveRDS(running_time, file = "/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/grouped_early_time_0.1.RDS")

```

```{r results}

nlambda = 50

metriche_res <-  list()

for (l in 1:length(SEED)){
metriche_res[[l]] <- lapply(1:nlambda, function(i){
  metrics(net200, net200_results[[l]]$network[[i]])
})
metriche_res[[l]] <- data.frame(do.call(rbind, metriche_res[[l]]))
}

# Let's add the column relative to lambda values and to the Youden J statistic

for(i in 1:length(metriche_res)){
  metriche_res[[i]]$Lambda <- net200_results[[i]]$lambda
  metriche_res[[i]]$J <- metriche_res[[i]]$TPR - metriche_res[[i]]$FPR
}


mean_metriche_res <- Reduce("+", metriche_res)
mean_metriche_res <- mean_metriche_res/length(metriche_res)

saveRDS(metriche_res, file = "/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/metriche_grouped_early_0.1.RDS")

```


Here we plot the results:
```{r Plots}
source("/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/R/Graphical_Functions.R")
for(i in 1:length(SEED)){
pdf(file = paste0("/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/grouped_early_0.1_",i,".pdf"), width = 15, height = 15)

print(
  ggpubr::ggarrange(roc(metriche_res[[i]]),
          prc(metriche_res[[i]]),
          Accuracy(metriche_res[[i]]),
          F1_stat(metriche_res[[i]]),
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
)


dev.off()
}

pdf(file = "/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/MEAN_grouped_early_0.1.pdf", width = 15, height = 15)

  ggpubr::ggarrange(roc(mean_metriche_res),
          prc(mean_metriche_res),
          Accuracy(mean_metriche_res),
          F1_stat(mean_metriche_res),
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)

dev.off()

```

```{r straightforward grouped method}

# abbiamo anche inserito nell'output i warnings e la itermat
available = parallel::detectCores(logical = FALSE)
ncores <- available - 1 


# Qui salveremo i tempi impiegati da ciascuna realizzazione
running_time <- list()
# Qui l'output
net200_results <- list()

for (i in 1:length(Xs_0.1)){
  running_time[[i]] <- system.time({
    net200_results[[i]] <- zinb_LGM_grp(Xs_0.1[[i]], sym = "AND", nCores = ncores, verbose = 1)
  })[3]
}

mean(sapply(running_time, function(x) x/60))

saveRDS(net200_results, file = "/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/grouped_res_0.1.RDS")
saveRDS(running_time, file = "/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/grouped_time_0.1.RDS")

```

```{r results}

nlambda = 50

metriche_res <-  list()

for (l in 1:length(SEED)){
metriche_res[[l]] <- lapply(1:nlambda, function(i){
  metrics(net200, net200_results[[l]]$network[[i]])
})
metriche_res[[l]] <- data.frame(do.call(rbind, metriche_res[[l]]))
}

# Let's add the column relative to lambda values and to the Youden J statistic

for(i in 1:length(metriche_res)){
  metriche_res[[i]]$Lambda <- net200_results[[i]]$lambda
  metriche_res[[i]]$J <- metriche_res[[i]]$TPR - metriche_res[[i]]$FPR
}


mean_metriche_res <- Reduce("+", metriche_res)
mean_metriche_res <- mean_metriche_res/length(metriche_res)

saveRDS(metriche_res, file = "/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/MEAN_grouped_res_0.1.RDS")

```


Here we plot the results:
```{r Plots}
for(i in 1:length(SEED)){
pdf(file = paste0("/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/grouped_0.1_",i,".pdf"), width = 15, height = 15)

print(
  ggpubr::ggarrange(roc(metriche_res[[i]]),
          prc(metriche_res[[i]]),
          Accuracy(metriche_res[[i]]),
          F1_stat(metriche_res[[i]]),
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
)


dev.off()
}

pdf(file = "/home/negus/Desktop/Link to Francesco/PhD Project/Scripts/Bisection_Grid/DataSimRzinb/net200_100/MEAN_grouped_0.1.pdf", width = 15, height = 15)

  ggpubr::ggarrange(roc(mean_metriche_res),
          prc(mean_metriche_res),
          Accuracy(mean_metriche_res),
          F1_stat(mean_metriche_res),
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)

dev.off()

```
